name: ir-curios
version: 0.1.0.0
github: "valmirjunior0088/ir-curios"
license: BSD3
author: "Valmir Pretto"
maintainer: "valmirjunior0088 dot gmail dot com"
copyright: "(2022 - present) Valmir Pretto"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/valmirjunior0088/ir-curios#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2 && < 3
- bytestring >= 0.10 && < 1
- megaparsec >= 9.2 && < 10

# Lens specific dependencies
- lens >= 5.0 && < 6
- generic-lens >= 2.2 && < 3

default-extensions:
- BinaryLiterals
- LambdaCase
- ParallelListComp
- NamedFieldPuns
- NoFieldSelectors
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving

# Lens specific extensions
- DeriveGeneric
- DataKinds
- TypeApplications

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ir-curios-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ir-curios
